services:
   ifixit_akeneo.edit_page_redirector.controller:
      public: true
      class: iFixit\Akeneo\iFixitBundle\Controller\EditPageRedirectorController
      arguments:
         - '@pim_catalog.repository.product_model'
         - '@pim_catalog.repository.product'
