edit_product_redirector:
    path: /redirect/edit/product/{sku}
    controller: ifixit_akeneo.edit_page_redirector.controller::redirectToProduct
    methods: [GET]
    requirements:
        sku: \d{7,8}
edit_product_model_redirector:
    path: /redirect/edit/product/{productcode}
    controller: ifixit_akeneo.edit_page_redirector.controller::redirectToProductModel
    methods: [GET]
    requirements:
        productcode: \d{6}
