services:
   postsave.listener:
      class: iFixit\Akeneo\iFixitBundle\EventListener\PostSaveListener
      arguments:
         - '@ifixit_akeneo.ifixit_api'
      tags:
         - { name: kernel.event_listener, event: akeneo.storage.pre_save, method: onPreSave }
         - { name: kernel.event_listener, event: akeneo.storage.pre_save_all, method: onPreSaveAll }
         - { name: kernel.event_listener, event: akeneo.storage.post_save_all, method: onPostSaveAll }
         - { name: kernel.event_listener, event: akeneo.storage.post_save, method: onPostSave }

   postremove.listener:
      class: iFixit\Akeneo\iFixitBundle\EventListener\PostRemoveListener
      arguments:
         - '@ifixit_akeneo.ifixit_api'
      tags:
         - { name: kernel.event_listener, event: akeneo.storage.post_remove, method: onPostRemove }

   ifixit_akeneo.ifixit_api:
      class: iFixit\Akeneo\iFixitBundle\EventListener\iFixitApi
      arguments:
        - '@ifixit_akeneo.config'
        - '@logger'

   ifixit_akeneo.config:
      class: iFixit\Akeneo\iFixitBundle\iFixitConfig

   pim_catalog.updater.setter.price_collection_value:
      class: iFixit\Akeneo\PriceCollectionAttributeSetter
      parent: pim_catalog.updater.setter.abstract
      arguments:
         - '@pim_catalog.updater.adder.price_collection_value'
         - ['pim_catalog_price_collection']
      tags:
         - { name: 'pim_catalog.updater.setter' }
